apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental
  labels:
    app: rental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental
  template:
    metadata:
      labels:
        app: rental
    spec:
      containers:
        - name: rental
          image: clivezhang/coolcar_rental:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: ADDR
              value: :8081
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: mongo
                  name: endpoints
            - name: CAR_ADDR
              valueFrom:
                configMapKeyRef:
                  key: car
                  name: endpoints
            - name: AI_ADDR
              valueFrom:
                configMapKeyRef:
                  key: ai
                  name: endpoints
            - name: AUTH_PUBLIC_KEY_FILE
              value: /sec/public.key
          volumeMounts:
            - mountPath: /sec
              name: auth
          livenessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-addr", ":8081"]
      imagePullSecrets:
        - name: hub.docker.com
      volumes:
        - name: auth
          secret:
            secretName: auth
            items:
              - key: publicKey
                path: public.key

---
apiVersion: v1
kind: Service
metadata:
  name: rental
spec:
  selector:
    app: rental
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  type: ClusterIP
